//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wzic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class artist
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Quote { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string Twister { get; set; }
        public string Img { get; set; }
    }
}
