//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wzic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class song
    {
        public int ID_Song { get; set; }
        public string titile_song { get; set; }
        public string artist_song { get; set; }
        public string title_and_artist { get; set; }
        public string file_song { get; set; }
    }
}
